name: destek_saci
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/u_profil.png
    - assets/icons/c_profil.png
    - assets/icons/g_profil.png
    - assets/icons/acik_kutu.png
    - assets/icons/app_icon.png

flutter_native_splash:
  color: "#ffffff" # Arka plan rengi (beyaz)
  image: assets/icons/app_icon.png
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
